name: avsr2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - six
  - ffmpeg<5  
  - pip:
    - sentencepiece
    - av
    - hydra-core
    